### ISSUE TITLE
Error 400 in submission

### ISSUE THREAD

**Issue by PJXIO-Dev** [tienthanh214/googleform-autofill-and-submit#7]
I tried the code on two different forms. The first one worked perfectly fine. The other form shows after inserting all the inputs the following:

`
Error! Can't submit form 400
Done!!!
`
And it didn't submit the form. both forms are open and can insert a response on them. Tried to investigate but it is a dead-end

**Comment by tienthanh214** [comment]
Could you please give me the example inputs or the link to the form you failed?

**Comment by tienthanh214** [comment]
You can try to customize the function `fill_random_value` in [main.py](https://github.com/tienthanh214/googleform-autofill-and-submit/blob/main/main.py), and run it. It might be better than customizing form.py

**Comment by tienthanh214** [comment]
You can simply find the `entry_id` of that field and write an **if** instead of customizing the `type_id` as you mentioned, this will apply in all fields with the same type.

You can try to run `python form.py <your-form-url>` to get the entry_id of the field you need.
Then edit the code like:
```py
# Customize for specific entry_id
if entry_id == 1545889152:
    return "It's work"
# Random value for each type
if type_id in [0, 1]: # Short answer and Paragraph
    return ''
...
 ```
Btw, i plan to modify the function interface (e.g., add the form field name as a parameter), making the script more flexible to customize.
 
 Thank you!
